name: 'Depploy Terraform IaC'

on:
  workflow_call:
    inputs:
      TERRAFORM_VAR_STRING:
        required: false
        type: string
      TERRAFORM_VAR_NAME:
        required: false
        type: string
      TERRAFORM_IAC_REPO:
        type: string
      TERRAFORM_IAC_REPO_PATH:
        type: string
    secrets:
      TF_API_TOKEN:
        required: true
      GIT_TOKEN:
        required: true
      MODULE_SSH_KEY:
        required: true

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions: write-all

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:

#     - name: Checkout
#       uses: actions/checkout@v3
#       with:
#         # Repository name with owner. For example, actions/checkout
#         # Default: ${{ github.repository }}
#         repository: ${{ inputs.TERRAFORM_IAC_REPO}}
#         #path: ./${{ inputs.TERRAFORM_IAC_REPO_PATH }}
#         ssh-key: ${{ secrets.GIT_TOKEN }}
    

    - name: Generate API module
      env:
        GITHUB_TOKEN: ${{ secrets.MODULE_SSH_KEY }}
      run: |
        
        git config user.name "anatoliihoodoo"
        git config user.email "anatolii.vorobiov@hoodoo.software"
        
        git clone https://anatoliihoodoo:$GITHUB_TOKEN@github.com/${{ inputs.TERRAFORM_IAC_REPO }}.git --branch=main main
        
        ls
        cd ${{ inputs.TERRAFORM_IAC_REPO_PATH }}
        
        git remote show origin
        
        # git checkout -b api-version-$COMMIT

        # touch new-file.sh
        # git add new-file.sh
        
        sed -i '/#variable placeholder ${{ inputs.TERRAFORM_VAR_NAME}}/c\ default="${{ inputs.TERRAFORM_VAR_STRING }}" #variable placeholder ${{ inputs.TERRAFORM_VAR_NAME}}' variables.tf
        git add .
        #git commit -m "Version of ${{ inputs.TERRAFORM_VAR_NAME}} updated to ${{ inputs.TERRAFORM_VAR_STRING }}"

        #git remote -v # Prints:
        #COMMENTED origin ***github.com/owner/my-repo.git (fetch)
        #COMMENTED origin ***github.com/owner/my-repo.git (push)
        
        #COMMENTED git config --unset-all http.https://github.com/.extraheader
        #git config -l | grep 'http\..*\.extraheader' | cut -d= -f1 |  xargs -L1 git config --unset-all
        #COMMENTED git push --set-upstream origin api-version-$COMMIT # This does not work
        #COMMENTED git push --set-upstream https://anatoliihoodoo:$GITHUB_TOKEN@github.com/${{ inputs.TERRAFORM_IAC_REPO }} main # This does not work either
        #git push --prune https://token:$GITHUB_TOKEN@github.com/${{ inputs.TERRAFORM_IAC_REPO }}.git


#     - name: Split Variable string
#       run: |
#         tree 
#         cd ${{ inputs.TERRAFORM_IAC_REPO_PATH }}
#         ls
#         sed -i '/#variable placeholder ${{ inputs.TERRAFORM_VAR_NAME}}/c\ default="${{ inputs.TERRAFORM_VAR_STRING }}" #variable placeholder ${{ inputs.TERRAFORM_VAR_NAME}}' variables.tf
#         cat variables.tf
        
#     - name: Commit and push changes
#       uses: devops-infra/action-commit-push@master
#       with:
#         github_token: ${{ secrets.MODULE_SSH_KEY }}
#         commit_message: Version of ${{ inputs.TERRAFORM_VAR_NAME}} updated to ${{ inputs.TERRAFORM_VAR_STRING }}
          
          
          
#     - name: Pushes to another repository
#       uses: cpina/github-action-push-to-another-repository@main
#       env:
# #         SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
#         API_TOKEN_GITHUB: ${{ secrets.MODULE_SSH_KEY }}
#       with:
#         source-directory: ${{ inputs.TERRAFORM_IAC_REPO_PATH }}
#         destination-github-username: 'anatoliihoodoo'
#         destination-repository-name: '${{ inputs.TERRAFORM_IAC_REPO}}'
#         user-email: anatolii.vorobiov@hoodoo.software
#         target-branch: main
        
        
        
#     - name: Update resources
#       uses: test-room-7/action-update-file@v1
#       with:
#           file-path: ${{ inputs.TERRAFORM_IAC_REPO_PATH }}/variables.tf
#           commit-msg: Version of ${{ inputs.TERRAFORM_VAR_NAME}} updated to ${{ inputs.TERRAFORM_VAR_STRING }}
#           github-token: ${{ secrets.MODULE_SSH_KEY }}
#           committer-email: anatolii.vorobiov@hoodoo.software
        
