name: 'Depploy Terraform IaC'

on:
  workflow_call:
    inputs:
      TERRAFORM_VAR_STRING:
        required: false
        type: string
      TERRAFORM_VAR_NAME:
        required: false
        type: string
      TERRAFORM_IAC_REPO:
        type: string
      TERRAFORM_IAC_REPO_PATH:
        type: string
    secrets:
      TF_API_TOKEN:
        required: false
      GIT_TOKEN:
        required: true
      MODULE_SSH_KEY:
        required: false

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions: write-all

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        # Repository name with owner. For example, actions/checkout
        # Default: ${{ github.repository }}
        repository: ${{ inputs.TERRAFORM_IAC_REPO}}
        #path: ./${{ inputs.TERRAFORM_IAC_REPO_PATH }}
        ssh-key: ${{ secrets.GIT_TOKEN }}
    

    - name: Update variable file and push
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
      run: |
        
        git config user.name "anatoliihoodoo"
        git config user.email "anatolii.vorobiov@hoodoo.software"
        
        #git clone https://anatoliihoodoo:$GITHUB_TOKEN@github.com/${{ inputs.TERRAFORM_IAC_REPO }}.git --branch=main main
        
        #ls
        cd ${{ inputs.TERRAFORM_IAC_REPO_PATH }}
        #tree 
        git remote show origin
  
        #COMMENTED git checkout -b api-version-$COMMIT
        
        sed -i '/#variable placeholder ${{ inputs.TERRAFORM_VAR_NAME}}/c\ default="${{ inputs.TERRAFORM_VAR_STRING }}" #variable placeholder ${{ inputs.TERRAFORM_VAR_NAME}}' variables.tf
        git add .
        git commit -m "Version of ${{ inputs.TERRAFORM_VAR_NAME}} updated to ${{ inputs.TERRAFORM_VAR_STRING }}"

        #git remote -v # Prints:
                
        git remote rm origin
        #git remote add origin  https://anatoliihoodoo:$GITHUB_TOKEN@github.com/${{ inputs.TERRAFORM_IAC_REPO }}.git

        #git push --set-upstream origin main
        git remote add origin git@github.com:${{ inputs.TERRAFORM_IAC_REPO }}.git 
        git remote -v
        git fetch origin
        git push -u origin main

#     - name: Split Variable string
#       run: |
#         tree 
#         cd ${{ inputs.TERRAFORM_IAC_REPO_PATH }}
#         ls
#         sed -i '/#variable placeholder ${{ inputs.TERRAFORM_VAR_NAME}}/c\ default="${{ inputs.TERRAFORM_VAR_STRING }}" #variable placeholder ${{ inputs.TERRAFORM_VAR_NAME}}' variables.tf
#         cat variables.tf
 
        
