name: Deploy to Amazon EKS

on:
  workflow_call:
    inputs:
      AWS_REGION:
        required: true
        type: string
      EKS_CLUSTER:
        required: true
        type: string
      DEPLOYMENT_NAME:
        required: true
        type: string
      IMAGE_NAME:
        required: true
        type: string
      IMAGE_TAG:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
# env:
#   AWS_REGION: "ap-southeast-1"                   # set this to your preferred AWS region, e.g. us-west-1
#   EKS_CLUSTER: "ci-cd-eks"                 # set this to your Amazon ECS cluster name
  
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
#     - name: Go to folder
#       run: |
#         cd ${{ inputs.KUBERNETES_PATH }}
        
    - uses: azure/setup-kubectl@v2.0
#       with:
#         version: 'v.1.21.3' # default is latest stable
      id: install
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ inputs.AWS_REGION }}
    
    - name: Update kube config
      run: aws eks update-kubeconfig --name ${{ inputs.EKS_CLUSTER }} --region ${{ inputs.AWS_REGION }}

    - name: Deploy image to Amazon EKS
      run: |
        kubectl set image deployment/${{ inputs.DEPLOYMENT_NAME }} api=${{ inputs.IMAGE_NAME }}:${{ inputs.IMAGE_TAG }}
        kubectl set image deployment/${{ inputs.DEPLOYMENT_NAME }} sidekiq=${{ inputs.IMAGE_NAME }}:${{ inputs.IMAGE_TAG }}
        sleep 20
        kubectl exec deploy/${{ inputs.DEPLOYMENT_NAME }} -- ls 
