name: Reusable flow 1

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: false
        type: string
        default: 'production'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.BRANCH }}
        
   anotherone: 
    needs: deploy
    uses: hoodoo-software/ci-cd-workflow/.github/workflows/reusable-flow-2.yml@main
    with:
      IMAGE_TAG: "1.6.1.10" #${{ needs.job1.outputs.tag }}                  
      
