name: 'Validate Terraform IaC'

on:
  workflow_call:
    secrets:
      TF_TOKEN:
        required: true

jobs:
  terraform:
    name: 'Terraform validation'
    runs-on: ubuntu-latest
    timeout-minutes: 30

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2
      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
      - uses: terraform-linters/setup-tflint@v2
        name: Setup TFLint
        with:
          tflint_version: v0.38.1

      - name: Show version
        run: tflint --version

      - name: Init TFLint
        run: tflint --init

      - name: Run TFLint
        run: tflint -f compact
        
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          check: CKV_AWS_*, CKV_K8S_*, CKV_SECRET_*
          skip-check: CKV_AWS_38,CKV_AWS_39,CKV_AWS_130,CKV_AWS_144,CKV_K8S_29
          download_external_modules: true
          tfc_token: ${{ secrets.TF_TOKEN }}
          framework: all 
          
