name: Terraform modules validation
on:
  workflow_call:

jobs:
  tfsec:
    name: tfsec
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master
        
      - uses: terraform-linters/setup-tflint@v2
        name: Setup TFLint
        with:
          tflint_version: v0.38.1
      - name: Init TFLint
        run: tflint --init
      - name: Run TFLint
        run: tflint -f compact
        
      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          check: CKV_AWS_*, CKV_K8S_*, CKV_SECRET_*
          skip_check: CKV_AWS_38, CKV_AWS_39
          framework: all 
          
